site_name: PyToC
site_url: https://github.com/Tiago1604/compiladores_14

nav:
  - Home:
      - Sobre: index.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Metodologia: planejamento/metodologia.md
      - Ferramentas: planejamento/ferramentas.md
      - Planejamento das Sprints: planejamento/planejamento_das_sprints.md
  - Projeto Final:
      - Guia Detalhado: Projeto_Final/Guia_detalhado.md
      - Especificação do Projeto: Projeto_Final/Especificacao_do_projeto.md
  - Decisões Técnicas: decisoes/decisao.md
  - Problemas e Soluções: 
      - Problemas e Soluções 1: problemas_e_solucoes/problemas_e_solucoes1.md
      - Problemas e Soluções 2: problemas_e_solucoes/problemas_e_solucoes2.md
  - Atas de Reunião:
      - Ata 1: atas/ata1.md
      - Ata 2: atas/ata2.md
      - Ata 3: atas/ata3.md
      - Ata 4: atas/ata4.md
      - Ata 5: atas/ata5.md
  - Sprints:
      - Sprint: sprints/sprint.md
  - Atividades Semanais:
    - Semana 1: atividades_semanais/Semana1.md
    - Semana 2: atividades_semanais/Semana2.md
    - Semana 3: atividades_semanais/Semana3.md
    - Semana 4: atividades_semanais/Semana4.md
    - Semana 5: atividades_semanais/Semana5.md
    - Semana 6: atividades_semanais/Semana6.md
    - Semana 7: atividades_semanais/Semana7.md
    - Semana 8: atividades_semanais/Semana8.md
    - Semana 9: atividades_semanais/Semana9.md
    - Semana 10: atividades_semanais/Semana10.md
  - Ponto de Controle:
      - Ponto de Controle 1: ponto_de_controle/ponto_de_controle1.md
      - Ponto de Controle 2: ponto_de_controle/ponto_de_controle2.md
theme:
  logo: assets/logo.jpg
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    - scheme: light
      primary: custom
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
icon:
  repo: fontawesome/brands/git-alt
